import Head from 'next/head'

import SubmitButton from '../../components/Buttons/SubmitButton'
import { FormsContainer } from '../../styles/FormsContainer'

import { Container } from '@nextui-org/react'

import Forms from '../../components/Cards/Forms/Forms'

const customContainerStyle = {
  height:'87vh',
  display:'flex',
  alignItems:'center',
  justifyContent:'center',
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Web3dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container css={customContainerStyle} >
        <Container>
          <FormsContainer>
            <Forms />
            <SubmitButton />
          </FormsContainer>
        </Container>   
      </Container>  
    </>
  )
}
